// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include "matchview.h"
#include <FL/Fl_Pack.H>
#include <FL/Fl_Slider.H>

class UserInterface {
public:
  Fl_Window* make_window();
  MatchView *match_view;
  Fl_Slider *slider_match_length;
private:
  void cb_slider_match_length_i(Fl_Slider*, void*);
  static void cb_slider_match_length(Fl_Slider*, void*);
};
#endif
